### PR TITLE
Fix `code_inferred` under v1.8

### LINKED ISSUE #13: `code_inferred` doesn't work under Julia v1.8
```julia
julia> using CodeInfoTools

julia> f(x) = 2x
f (generic function with 1 method)

julia> code_inferred(f, Int) ### <----------- code_inferred doesn't work under v1.8
ERROR: MethodError: no method matching Core.Compiler.InferenceState(::Core.Compiler.InferenceResult, ::Core.CodeInfo, ::Bool, ::Core.Compiler.NativeInterpreter)
Closest candidates are:
  Core.Compiler.InferenceState(::Core.Compiler.InferenceResult, ::Core.CodeInfo, ::Symbol, ::Core.Compiler.AbstractInterpreter) at ~/Work/julia/julia/usr/share/julia/base/compiler/inferencestate.jl:72
  Core.Compiler.InferenceState(::Core.Compiler.InferenceResult, ::Symbol, ::Core.Compiler.AbstractInterpreter) at ~/Work/julia/julia/usr/share/julia/base/compiler/inferencestate.jl:246
Stacktrace:
 [1] code_inferred(mi::Core.MethodInstance; world::UInt64, interp::Core.Compiler.NativeInterpreter)
   @ CodeInfoTools ~/.julia/packages/CodeInfoTools/FiYK4/src/CodeInfoTools.jl:527
 [2] #36
   @ ./none:0 [inlined]
 [3] iterate
   @ ./generator.jl:47 [inlined]
 [4] collect(itr::Base.Generator{Vector{Core.MethodInstance}, CodeInfoTools.var"#36#37"{UInt64, Core.Compiler.NativeInterpreter}})
   @ Base ./array.jl:784
 [5] code_inferred(f::Any, types::Type{Tuple{Int64}}; world::UInt64, interp::Core.Compiler.NativeInterpreter)
   @ CodeInfoTools ~/.julia/packages/CodeInfoTools/FiYK4/src/CodeInfoTools.jl:542
 [6] code_inferred(f::Any, t::Type; world::UInt64, interp::Core.Compiler.NativeInterpreter)
   @ CodeInfoTools ~/.julia/packages/CodeInfoTools/FiYK4/src/CodeInfoTools.jl:549
 [7] code_inferred(f::Any, t::Type)
   @ CodeInfoTools ~/.julia/packages/CodeInfoTools/FiYK4/src/CodeInfoTools.jl:549
 [8] top-level scope
   @ REPL[3]:1

julia> VERSION
v"1.8.0-DEV.1418"
julia> code_info(f, Int)  ### <----------- code_info works under v1.8
CodeInfo(
1 ─ %1 = 2 * x
└──      return %1
)

```

### PR DESCRIPTION
**Pull request by KDr2**
Fix #13

### CODE REVIEW

File: src/CodeInfoTools.jl [hunk 1]
```diff
@@ -558,7 +558,11 @@ function code_inferred(mi::Core.Compiler.MethodInstance;
     src.inferred && return src
     Core.Compiler.validate_code_in_debug_mode(result.linfo, 
                                               src, "lowered")
-    frame = Core.Compiler.InferenceState(result, src, false, interp)
+    frame = @static if VERSION.major == 1 && VERSION.minor < 8
```
Comment (devmotion) [inline src/CodeInfoTools.jl:561]: Maybe use
```suggestion
    frame = @static if VERSION < v"1.8"
```
(BTW I just learnt today that usually `@static` is not needed). Maybe it would be even better to figure out the Github commit in the Julia base repo where this change was introduced to be able to branch more accurately.
